#!/usr/bin/python3
import tornado.gen
import tornado.ioloop
from database.user import User
import prj
    
    
def get_args():
    from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter

    parser = ArgumentParser(description="Manual add user to database", formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument("--login", type=str, default="admin", help="Login")
    parser.add_argument("--password", type=str, default="admin", help="Password")
    parser.add_argument("--email", type=str, default=prj.mailer["email"], help="E-Mail")
    parser.add_argument("--group", type=str, default="admin", help="Access level", choices=User.getSortedAccessNames())
    return parser.parse_args()


if __name__ == "__main__":
    
    args = get_args()
    
    @tornado.gen.coroutine
    def add_user():
        yield User.insert(
            confirmed=True, 
            access_level=User.getAccessNameLevel(args.group), 
            login=args.login, 
            password=args.password, 
            email=args.email)
        
    tornado.ioloop.IOLoop.instance().run_sync(add_user)