#!/usr/bin/python3
from daemons import mailer, mailconfirm, webui
import logging
import prj


def get_args():

    from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
    
    parser = ArgumentParser(description="{title} server".format(**prj.app), formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument("--verbosity", type=str, default=prj.app["verbosity"], help="Verbosity level")
    parser.add_argument("--port", type=int, default=12345, help="WebUI port")
    return parser.parse_args()


if __name__ == "__main__":

    args = get_args()
    logging.getLogger().setLevel(getattr(logging, args.verbosity.upper()))

    mailer.Mailer().start()
    mailconfirm.MailConfirmer().start()
    webui.WebUI(port=args.port).start()